#+TITLE: LaTeX 学习感想
#+AUTHOR: zhcosin@163.com


用 LaTeX 有一年多了，我是一名数学爱好者，平时的主要精力主要用在数学上，所以对 LaTeX 以使用为主，并没有什么深入研究，我的 LaTeX 知识也就基本限于写作数学文档和书籍所需要用到的知识而已，所以本文标题中的“学习感想”四个字，其实不太准确，应该是“使用感想”才对。

以下谈一下我的一些体会.

* LaTeX 是最专业的科技图书排版系统

LaTeX 是当今世界非常专业的排版系统，它排版的数学公式尤其精美，[[https://coding.net/u/zhcosin/p/math-notes-publish/git/blob/master/elementary-math-notes.pdf][这里]] 有一份我的数学笔记，读者可以看到它的效果，这还是尽量使用默认设置，没有各种花哨的版式。

排版效果精美当然是它最根本的优点，总结起来，它的优点如下:
  - 排版专业，数学公式精致.
  - 源文件为文本文件，便于像 git 这样的版本管理软件管理.
  - 大量的宏包支持，有能力可以自己编写宏包扩展功能.
  - 开源软件，无需破解激活.
  - 跨平台，无论你使用的是 windows，还是 linux 还是 mac，都一样支持.
    
当然它也不是没有缺点的，比如:
  - 不是所见即所得，需要编译生成pdf文档. (这个算不算缺点另说，但这点是不必讳言的，毕竟很多人习惯了 word 的观念.)
  - 入门有一定难度.
  - 软件从编辑器到套件到宏包到编译引擎，初学者可能会一头雾水.
    
以下就谈一些看法。

* 关于 LaTeX 的入门难度

LaTeX 虽然排版漂亮，但是入门有一定难度，其实这里所说的难是相对于 word 这类大众化的工具而言的，学习使用 LaTeX 肯定要比 word 多花一些时间和精力，但如果你是一个经常需要写作的人，那么你付出的这些时间和精力将是值得的，如果你只是一眼看到排版效果很漂亮头脑发热决定要折腾一番，那么你多半会寸步难行，因为 LaTeX 绝不可能在几分钟之内学会，事实上，按照正常人的学习进度，在零基础的前提下，光是通读一遍《一份不太简短的 LaTeX2e 介绍》，就要花费你一个下午的时间。

* 入门一定要通读一遍教程

那有什么好办法吗？有，那就是入门的时候，一定不要偷懒，一定要通读一遍教程，推荐《一份不太简短的 LaTeX2e 介绍》，从文档组织结构、到图片和表格的插入，再到如何使用中文，再到编译方式，都要有个了解，对用 LaTeX 写作的工作方式有一些概念，才不致于总是被一些低级问题所困扰。有些人一上来，以为 LaTeX 不过是 word 的一个替代品，第一个问题就是问软件在哪里下载，怎么安装，安装后打开软件点哪个按键哪个菜单等等，这完全就是在用 word 的操作观念，以为 LaTeX 也就是一个软件，只要打开后点选一些菜单和按钮，就能排版出文档，这当然是在乱弹琴，最后的结果就是在怎么也搞不清状态的情况下直接放弃，这事实上也涉及到另一个问题，那就是图形界面软件和命令行软件的区别，当然对于这种类型的人来说也无意去了解了。

* 入门不要套用模板

另一个就是，不要一上来就折腾模板，有的人在看了一遍教程后会觉得，我想要一个漂亮的版式，我现在没有能力自己定制，我就拿别人的模板直接套用，但是在 LaTeX 的世界，模板真不是刚入门的人可以玩的，如果编译顺利倒还好，要是编译有问题那基本上是你搞不定的问题，除非你能看懂模板代码，这显然也不是刚入门的人力所能及的。我的建议是，一开始尽量使用默认设置，尽量不要弄各种花哨的版式，等到你有一定的使用经验后，再来折腾版式不迟。

* 用到某个功能时再去学它

LaTeX 的功能很多，可以写作短篇文档，也可以写作长篇书籍，当然在两种情况下，需要解决的问题也不尽相同，比如写文档的时候，要考虑的就是目录结构、标记与引用、图片和表格这些问题，而在写书的时候，还要考虑前言、参考文献的引用、索引等问题，这些东西都不可能在很短的时间内就学会，我的建议是，现学现用，当你需要用到什么功能时，就去学习这个功能的使用，比如你一入门的时候，肯定是试写一下最简单的文档，当你准备弄插图的时候，就去研究一下插图功能，当你准备写书的时候，你就去研究一下怎么写参考文献等等。这样你用的时间越久，你用到的功能越多，你学到的就越多。

* 写出一份书籍并不需要掌握太多 LaTeX 知识

据我写作笔记的经验，要排版出一份像样的书籍，其实并不需要太多的 LaTeX 知识，我至今 LaTeX 水平也有限，基本不只进行简单的定制，复杂的定制就只会套用现成的代码。以我的数学笔记为例，只要用到如下 LaTeX 知识: 书籍文档的组织结构、CTeX 文档类、文本排版、数学公式的排版、定理和证明环境、标记与引用、脚注、插图、前言摘要目录参考文献(索引暂时没有)，基本上就这些内容，而且也不是全部都学会了才开始写，都是在用的过程中逐渐熟悉它。

* 试着用 LaTeX 写自己的笔记

这里所说的笔记，是指你在学习其他学科的时候所做的笔记，那么，是时候让 LaTeX 来排版你的个人笔记了，用起来吧，祝你好运。
